apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai-image-builder.envname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yatai-image-builder.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_IMAGE_BUILDER_SHARED_ENV_SECRET_NAME: {{ include "yatai-image-builder.shared-envname" . }}

  YATAI_SYSTEM_NAMESPACE: {{ .Values.yataiSystem.namespace }}
  YATAI_API_TOKEN: {{ include "yatai-image-builder.yataiApiToken" . | quote }}

  DOCKER_REGISTRY_SERVER: {{ .Values.dockerRegistry.server | quote }}
  DOCKER_REGISTRY_IN_CLUSTER_SERVER: {{ .Values.dockerRegistry.inClusterServer | quote }}
  DOCKER_REGISTRY_USERNAME: {{ .Values.dockerRegistry.username | quote }}
  {{- if not .Values.dockerRegistry.passwordExistingSecretName }}
  DOCKER_REGISTRY_PASSWORD: {{ .Values.dockerRegistry.password | quote }}
  {{- end }}
  DOCKER_REGISTRY_SECURE: {{ .Values.dockerRegistry.secure | quote }}
  DOCKER_REGISTRY_BENTO_REPOSITORY_NAME: {{ .Values.dockerRegistry.bentoRepositoryName | quote }}

  INTERNAL_IMAGES_CURL: {{ .Values.internalImages.curl | quote }}
  INTERNAL_IMAGES_KANIKO: {{ .Values.internalImages.kaniko | quote }}
